feat(language-service): add style scoped completion
vuejs/language-tools pull request #4705
Opened 2024-08-18 14:31 UTC by runyasak

# Overview

I've added the scoped attribute to style completion items.
Now, when we type style in completion, scoped is available as an option.

# Screenshots

https://github.com/user-attachments/assets/a2a2c236-b82c-43ee-a7a6-b2b548149ce8

---

This is my first PR. If you have any feedback or suggestions, please do not hesitate to let me know.

2024-08-18 16:02 UTC, KazariEX commented
I think there is no need to extract languages to the top level, as it might be obtained from providers in the future. #4645 

What about `module`?

2024-08-18 17:28 UTC, runyasak commented
> I think there is no need to extract languages to the top level, as it might be obtained from provider in the future. #4645
> 
> What about `module`?

Hi @KazariEX, I apologize for not seeing your PR earlier.
Are you referring to [CSS Modules](https://vuejs.org/api/sfc-css-features.html#css-modules)?
If no one is assigned to this feature, may I contribute to it?
Should I create a new PR or update this one?

2024-08-18 17:39 UTC, KazariEX commented
Just update directly, I think they belong to the same feature.

2024-08-18 18:03 UTC, runyasak commented
@KazariEX I've updated my PR to `module`.
Please review my code again.

2024-08-18 18:07 UTC, KazariEX commented
Sorry I didn't mean replacement but both `scoped` and `module`.

2024-08-18 18:07 UTC, KazariEX commented on packages/language-service/lib/plugins/vue-sfc.ts
> +	module = false,
```suggestion
	attr = '',
```

2024-08-18 18:08 UTC, KazariEX commented on packages/language-service/lib/plugins/vue-sfc.ts
> +		label: styleItem.label + ' lang="' + lang + '"' + (module ? ' module' : ''),
```suggestion
		label: styleItem.label + ' lang="' + lang + '"' + (attr ? ' ' + attr : ''),
```

2024-08-18 18:08 UTC, KazariEX commented on packages/language-service/lib/plugins/vue-sfc.ts
> +			newText: styleItem.textEdit.newText + ' lang="' + lang + '"' + (module ? ' module' : ''),
```suggestion
			newText: styleItem.textEdit.newText + ' lang="' + lang + '"' + (attr ? ' ' + attr : ''),
```

2024-08-18 18:08 UTC, runyasak commented
> Sorry I didn't mean replacement but both `scoped` and `module`.

No problem. I will update now.

2024-08-18 18:09 UTC, KazariEX requested changes
Maybe we can do this.

2024-08-18 18:19 UTC, runyasak commented
@KazariEX  I've updated my PR with `attr` as your suggestion.
Please review my PR again.

2024-08-18 18:21 UTC, KazariEX approved these changes

2024-08-26 00:01 UTC, johnsoncodehk commented
LGTM, thanks!

2024-08-26 00:01 UTC, merged