fix: default to empty array if no signatures are found
vuejs/language-tools pull request #4930
Opened 2024-10-18 10:56 UTC by Hannesrasmussen

In certain cases, `signatures[0].parameters[0]` returns undefined. In those cases, we should just return an empty array instead of causing an error.

2024-10-18 11:01 UTC, KazariEX requested changes

2024-10-18 11:01 UTC, KazariEX commented on packages/component-meta/lib/base.ts
> +		const paramType = signatures.length > 0 ? signatures[0].parameters[0] : [];
```suggestion
		const paramType = signatures[0]?.parameters[0];
```

2024-10-18 11:55 UTC, KazariEX approved these changes

2024-10-25 01:30 UTC, johnsoncodehk approved these changes

2024-10-25 01:30 UTC, merged